### ISSUE TITLE
Invalid or unknown abi 16 for function "_ZGVnN4v_cosf"

### ISSUE THREAD

**Issue by jkbz64** [pgcentralfoundation/pgrx#1429]
I'm getting issues building clean pgrx extension using `cargo pgrx new` on `Linux 6.6.3-402.asahi.fc39.aarch64+16k aarch64 unknown` 

```
error: failed to run custom build command for `pgrx-pg-sys v0.11.2`

Caused by:
  process didn't exit successfully: `/home/jk/ext/target/debug/build/pgrx-pg-sys-80f4e82c3ebc282b/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=PGRX_BUILD_VERBOSE
  cargo:rerun-if-env-changed=PGRX_PG_SYS_GENERATE_BINDINGS_FOR_RELEASE
  cargo:rerun-if-env-changed=PGRX_PG_CONFIG_PATH
  cargo:rerun-if-env-changed=PGRX_PG_CONFIG_AS_ENV
  cargo:rerun-if-env-changed=LLVM_CONFIG_PATH
  cargo:rerun-if-env-changed=LIBCLANG_PATH
  cargo:rerun-if-env-changed=LIBCLANG_STATIC_PATH
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64_unknown_linux_gnu
  cargo:rerun-if-env-changed=PGRX_PG_SYS_GENERATE_BINDINGS_FOR_RELEASE
  cargo:rerun-if-changed=include
  cargo:rerun-if-changed=cshim
  cargo:rerun-if-changed=/home/jk/.pgrx/config.toml
  cargo:rerun-if-env-changed=PGRX_TARGET_INFO_PATH_PG13_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PGRX_TARGET_INFO_PATH_PG13
  cargo:rerun-if-env-changed=PGRX_BINDGEN_NO_DETECT_INCLUDES_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PGRX_BINDGEN_NO_DETECT_INCLUDES
  cargo:rerun-if-env-changed=PGRX_INCLUDEDIR_SERVER_PG13_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PGRX_INCLUDEDIR_SERVER_PG13
  cargo:rerun-if-env-changed=PGRX_INCLUDEDIR_SERVER_aarch64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PGRX_INCLUDEDIR_SERVER

  --- stderr
  build_paths=BuildPaths { manifest_dir: "/home/jk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.11.2", out_dir: "/home/jk/ext/target/debug/build/pgrx-pg-sys-57064a5f5b28a194/out", src_dir: "/home/jk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.11.2/src/include", shim_src: "/home/jk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.11.2/cshim", shim_dst: "/home/jk/ext/target/debug/build/pgrx-pg-sys-57064a5f5b28a194/out/cshim" }
  Generating bindings for pg13
  pg_config --configure CLANG = None
  Bindgen found clang version 17.0.4 (Fedora 17.0.4-1.fc39)
  found libclang at /usr/lib64/libclang.so.17.0.4
  Found include dirs ["/usr/lib/clang/17/include"]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/port.h:185:70: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/port.h:187:55: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/port.h:189:58: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/port.h:191:43: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:157:40: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:158:49: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:161:30: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:161:56: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:163:43: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:164:52: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:166:47: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:170:31: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:170:57: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:173:30: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:173:56: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:175:41: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:189:48: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:221:54: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/elog.h:437:47: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/palloc.h:155:44: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/utils/palloc.h:156:80: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/lib/stringinfo.h:96:67: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  clang diag: /home/jk/.pgrx/13.13/pgrx-install/include/postgresql/server/lib/stringinfo.h:107:78: warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
  thread '<unnamed>' panicked at /home/jk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.68.1/codegen/mod.rs:4195:17:
  Invalid or unknown abi 16 for function "_ZGVnN4v_cosf" (Function { name: "_ZGVnN4v_cosf", mangled_name: Some("_ZGVnN4v_cosf"), link_name: None, signature: TypeId(ItemId(24286)), kind: Function, linkage: External })
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread 'main' panicked at /home/jk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.11.2/build.rs:201:41:
  thread panicked while generating bindings: Any { .. }
```

**Comment by eeeebbbbrrrr** [comment]
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 
Can you do this, please?

Also, some more details about the host environment would be helpful.  Linux distro in particular.

**Comment by jkbz64** [comment]
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
  thread '<unnamed>' panicked at /home/jk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.68.1/codegen/mod.rs:4195:17:
  Invalid or unknown abi 16 for function "_ZGVnN4v_cosf" (Function { name: "_ZGVnN4v_cosf", mangled_name: Some("_ZGVnN4v_cosf"), link_name: None, signature: TypeId(ItemId(24286)), kind: Function, linkage: External })
  stack backtrace:
     0:     0xaaab26b1433c - std::backtrace_rs::backtrace::libunwind::trace::he8a67326ac20de3d
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0xaaab26b1433c - std::backtrace_rs::backtrace::trace_unsynchronized::hfd3a9a5f55ff1131
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0xaaab26b1433c - std::sys_common::backtrace::_print_fmt::hb49a851102ceca5b
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
     3:     0xaaab26b1433c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h15f1f2e31212c870
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
     4:     0xaaab26b3ba74 - core::fmt::rt::Argument::fmt::h2cc7b7defd4bd709
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
     5:     0xaaab26b3ba74 - core::fmt::write::hcf4aba49bf7d7245
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
     6:     0xaaab26b10e80 - std::io::Write::write_fmt::h81fd88916fa33e23
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
     7:     0xaaab26b14170 - std::sys_common::backtrace::_print::h2b57c890ca3e2251
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
     8:     0xaaab26b14170 - std::sys_common::backtrace::print::h17d1f7104a5ac9c3
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
     9:     0xaaab26b15fec - std::panicking::default_hook::{{closure}}::hc9e8486760244c57
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
    10:     0xaaab26b15d00 - std::panicking::default_hook::h7241adbb3d34c347
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
    11:     0xaaab26b165a8 - std::panicking::rust_panic_with_hook::h3d0cfe15782a2320
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
    12:     0xaaab26b16470 - std::panicking::begin_panic_handler::{{closure}}::h863571771fcdc96f
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
    13:     0xaaab26b14820 - std::sys_common::backtrace::__rust_end_short_backtrace::hbdb82b313780cdb0
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
    14:     0xaaab26b161c8 - rust_begin_unwind
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
    15:     0xaaab264234e8 - core::panicking::panic_fmt::hc665e63871657893
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
    16:     0xaaab2672c240 - <bindgen::ir::function::Function as bindgen::codegen::CodeGenerator>::codegen::h224e5486c1eace32
    17:     0xaaab26728828 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hcce962e70de207cc
    18:     0xaaab26748db8 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}::h3bbbc7ba4ff93c16
    19:     0xaaab26799820 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::h3b011e64dfaacd3e
    20:     0xaaab267287f8 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hcce962e70de207cc
    21:     0xaaab26754954 - bindgen::codegen::codegen::{{closure}}::h628a7710e278a87c
    22:     0xaaab267e0b98 - bindgen::ir::context::BindgenContext::gen::h165dfaba67e10e0f
    23:     0xaaab267543ac - bindgen::codegen::codegen::h616fdf20ad012ac4
    24:     0xaaab2678cde4 - bindgen::Bindings::generate::h50c6b04286dab569
    25:     0xaaab2678a55c - bindgen::Builder::generate::h8781cc9a37a9f5b3
    26:     0xaaab26435ea8 - build_script_build::run_bindgen::hd7983ba07a834683
    27:     0xaaab26434fb0 - build_script_build::get_bindings::h85095a68903c42de
    28:     0xaaab26430f50 - build_script_build::generate_bindings::h853b9a8def2fb6ea
    29:     0xaaab2643083c - build_script_build::main::{{closure}}::{{closure}}::{{closure}}::h91d9074833ea7cfe
    30:     0xaaab26445d84 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c892e648695a005
    31:     0xaaab264557d8 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::he8fc4f16d829caef
    32:     0xaaab26454384 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h70e0801f6583ad88
    33:     0xaaab26448ccc - std::panicking::try::do_call::h4eb107d201a2ceb7
    34:     0xaaab2644a510 - __rust_try
    35:     0xaaab26448b04 - std::panicking::try::h3e94343edfe0c031
    36:     0xaaab26455694 - std::thread::Builder::spawn_unchecked_::{{closure}}::h53284a0396b850f6
    37:     0xaaab2644af24 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h69c29a674b9a810a
    38:     0xaaab26b1bb28 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h62481b15919a9dd6
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
    39:     0xaaab26b1bb28 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfbc4072a0256f12c
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/boxed.rs:2007:9
    40:     0xaaab26b1bb28 - std::sys::unix::thread::Thread::new::thread_start::h0c641497d115225f
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys/unix/thread.rs:108:17
    41:     0xffff6f5f0584 - start_thread
    42:     0xffff6f65fc4c - thread_start
    43:                0x0 - <unknown>
  thread 'main' panicked at /home/jk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-pg-sys-0.11.2/build.rs:201:41:
  thread panicked while generating bindings: Any { .. }
  stack backtrace:
     0:     0xaaab26b1433c - std::backtrace_rs::backtrace::libunwind::trace::he8a67326ac20de3d
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0xaaab26b1433c - std::backtrace_rs::backtrace::trace_unsynchronized::hfd3a9a5f55ff1131
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0xaaab26b1433c - std::sys_common::backtrace::_print_fmt::hb49a851102ceca5b
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:67:5
     3:     0xaaab26b1433c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h15f1f2e31212c870
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:44:22
     4:     0xaaab26b3ba74 - core::fmt::rt::Argument::fmt::h2cc7b7defd4bd709
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
     5:     0xaaab26b3ba74 - core::fmt::write::hcf4aba49bf7d7245
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
     6:     0xaaab26b10e80 - std::io::Write::write_fmt::h81fd88916fa33e23
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/io/mod.rs:1763:15
     7:     0xaaab26b14170 - std::sys_common::backtrace::_print::h2b57c890ca3e2251
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:47:5
     8:     0xaaab26b14170 - std::sys_common::backtrace::print::h17d1f7104a5ac9c3
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:34:9
     9:     0xaaab26b15fec - std::panicking::default_hook::{{closure}}::hc9e8486760244c57
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:272:22
    10:     0xaaab26b15d00 - std::panicking::default_hook::h7241adbb3d34c347
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:292:9
    11:     0xaaab26b165a8 - std::panicking::rust_panic_with_hook::h3d0cfe15782a2320
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:731:13
    12:     0xaaab26b16470 - std::panicking::begin_panic_handler::{{closure}}::h863571771fcdc96f
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:609:13
    13:     0xaaab26b14820 - std::sys_common::backtrace::__rust_end_short_backtrace::hbdb82b313780cdb0
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/sys_common/backtrace.rs:170:18
    14:     0xaaab26b161c8 - rust_begin_unwind
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
    15:     0xaaab264234e8 - core::panicking::panic_fmt::hc665e63871657893
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
    16:     0xaaab264238d0 - core::result::unwrap_failed::h3732f7cb9991ea9b
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
    17:     0xaaab26460e3c - core::result::Result<T,E>::expect::h6a1abdddfef6d0de
    18:     0xaaab2643087c - build_script_build::main::{{closure}}::{{closure}}::hf69b6d7e93a13385
    19:     0xaaab2645bc4c - core::iter::adapters::map::map_fold::{{closure}}::h88b39a41566ff133
    20:     0xaaab26449574 - core::iter::traits::iterator::Iterator::fold::h294119bd445febf7
    21:     0xaaab26459f3c - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::hbc483e2c557186b2
    22:     0xaaab2645b2b4 - core::iter::traits::iterator::Iterator::for_each::hb5845e026b78ec4b
    23:     0xaaab2643ba08 - alloc::vec::Vec<T,A>::extend_trusted::hc83b41fcdb270e24
    24:     0xaaab2643db84 - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::hb5620491bf20cef5
    25:     0xaaab2643ad64 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::ha86912d5216830ad
    26:     0xaaab2643cdf4 - alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter::ha437825f07b35e03
    27:     0xaaab2643d9f4 - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h572d476577ea7f9a
    28:     0xaaab2645afec - core::iter::traits::iterator::Iterator::collect::hccca21ecedbad047
    29:     0xaaab26430758 - build_script_build::main::{{closure}}::h73c472950bb1b297
    30:     0xaaab264609f4 - std::thread::scoped::scope::{{closure}}::h79ea8234564ad7f6
    31:     0xaaab264543b4 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha4f4173e430782a7
    32:     0xaaab26448c84 - std::panicking::try::do_call::h27a6aa353ebafdd3
    33:     0xaaab2644a510 - __rust_try
    34:     0xaaab26448b98 - std::panicking::try::h69f985536a0f2ab4
    35:     0xaaab264607c8 - std::thread::scoped::scope::hcf37b800896c0d9e
    36:     0xaaab2642fcd0 - build_script_build::main::hc4f6b399c0d28d05
    37:     0xaaab2644b274 - core::ops::function::FnOnce::call_once::hdbd278408fa96daf
    38:     0xaaab26445d94 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd34fa6d7154d4429
    39:     0xaaab2645792c - std::rt::lang_start::{{closure}}::h55877556ea79c6fd
    40:     0xaaab26b0b938 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h5f6f1ef7d1871f43
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:284:13
    41:     0xaaab26b0b938 - std::panicking::try::do_call::h5ac962cba7365559
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
    42:     0xaaab26b0b938 - std::panicking::try::h7385069f6bec90c0
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
    43:     0xaaab26b0b938 - std::panic::catch_unwind::h4c10e3e3d2df879b
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
    44:     0xaaab26b0b938 - std::rt::lang_start_internal::{{closure}}::he094591eb38f6cd4
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:48
    45:     0xaaab26b0b938 - std::panicking::try::do_call::h889ff61306c27366
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
    46:     0xaaab26b0b938 - std::panicking::try::h81c61c3d25bed7e7
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
    47:     0xaaab26b0b938 - std::panic::catch_unwind::h2f06bb3fe3a59bb7
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
    48:     0xaaab26b0b938 - std::rt::lang_start_internal::h9dea485300561f65
                                 at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/rt.rs:148:20
    49:     0xaaab2645790c - std::rt::lang_start::hf108069808d62c53
    50:     0xaaab2643a000 - main
    51:     0xffff6f5909dc - __libc_start_call_main
    52:     0xffff6f590ab0 - __libc_start_main_alias_2
    53:     0xaaab26423b70 - _start
    54:                0x0 - <unknown>
```

> Also, some more details about the host environment would be helpful. Linux distro in particular.

Fedora 39 (fc39), Linux Asahi kernel, MBP M1 Pro
rustc 1.74.0 (79e9716c9 2023-11-13)
Bindgen found clang version 17.0.4 (Fedora 17.0.4-1.fc39)

**Comment by eeeebbbbrrrr** [comment]
I don't have an answer for you (yet), but Fedora has been really tough for us to consistency support.  It tends to fluctuate between "works great" and "oh, this is bizarre".

The fact this is panicking in `bindgen` makes me think it's confused about your system headers or libc or something.  This "cosf" function comes from `#include <math.h>`.  I thought maybe there was a same-named symbol in Postgres itself, but in fact (at least pg14) doesn't even contain the character sequence "cosf".  So... I dunno?

@thomcc any thoughts?

**Comment by usamoi** [comment]
It also happens in Arch Linux. However, cross compilation works with zig libc header files.

```sh
BINDGEN_EXTRA_CLANG_ARGS_aarch64_unknown_linux_gnu="-isystem /usr/lib/zig/libc/include/aarch64-linux-gnu -isystem /usr/lib/zig/libc/include/generic-glibc"
```

**Comment by workingjubilee** [comment]
This is a rust-bindgen issue specifically with aarch64, and it will depend on a new rust-bindgen release.

**Comment by workingjubilee** [comment]
It seems rust-bindgen has released a 0.69 version.

Nice.

I will try to port that into a pgrx 0.11.3 release.

**Comment by usamoi** [comment]
`v0.69.2` does not include the fix patch. `v0.70.0` might be needed.

**Comment by jkbz64** [comment]
It pulled `0.69.4` when upgrading to `0.11.3` and it now compiles for me, thank you!

**Comment by workingjubilee** [comment]
Wonderful!
