### ISSUE TITLE
pgx-pg-sys fails to compile on macOS

### ISSUE THREAD

**Issue by lostman** [pgcentralfoundation/pgrx#1608]
```
macOS 14.2.1 (23C71)
```

I have installed `pgx` and created a new package:

```
cargo pgx new testpgx
```

When I try to build, I'm getting this error:

```
cargo build
   Compiling pgx-pg-sys v0.7.4
error: failed to run custom build command for `pgx-pg-sys v0.7.4`

Caused by:
  process didn't exit successfully: `/private/tmp/testpgx/target/debug/build/pgx-pg-sys-d5fb9aa999de45df/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=PGX_PG_SYS_GENERATE_BINDINGS_FOR_RELEASE
  cargo:rerun-if-changed=/Users/mw/.pgx/config.toml
  cargo:rerun-if-changed=include
  cargo:rerun-if-changed=cshim
  cargo:rerun-if-env-changed=PGX_PG_CONFIG_PATH
  cargo:rerun-if-env-changed=PGX_PG_CONFIG_AS_ENV
  cargo:rerun-if-env-changed=LLVM_CONFIG_PATH
  cargo:rerun-if-env-changed=LIBCLANG_PATH
  cargo:rerun-if-env-changed=LIBCLANG_STATIC_PATH
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64-apple-darwin
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64_apple_darwin
  cargo:rerun-if-env-changed=PGX_TARGET_INFO_PATH_PG15_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PGX_TARGET_INFO_PATH_PG15
  cargo:rerun-if-env-changed=PGX_INCLUDEDIR_SERVER_PG15_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PGX_INCLUDEDIR_SERVER_PG15
  cargo:rerun-if-env-changed=PGX_INCLUDEDIR_SERVER_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PGX_INCLUDEDIR_SERVER
  cargo:rerun-if-env-changed=PGX_BINDGEN_NO_DETECT_INCLUDES_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PGX_BINDGEN_NO_DETECT_INCLUDES

  --- stderr
  build_paths=BuildPaths { manifest_dir: "/Users/mw/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgx-pg-sys-0.7.4", out_dir: "/private/tmp/testpgx/target/debug/build/pgx-pg-sys-439290c237504691/out", src_dir: "/Users/mw/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgx-pg-sys-0.7.4/src", shim_src: "/Users/mw/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgx-pg-sys-0.7.4/cshim", shim_dst: "/private/tmp/testpgx/target/debug/build/pgx-pg-sys-439290c237504691/out/cshim" }
  Generating bindings for pg15
  thread '<unnamed>' panicked at /Users/mw/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.60.1/src/ir/context.rs:861:9:
  "wait_struct_(unnamed_at_/Library/Developer/CommandLineTools/SDKs/MacOSX14_2_sdk/usr/include/sys/wait_h_199_2)" is not a valid Ident
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread 'main' panicked at /Users/mw/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pgx-pg-sys-0.7.4/build.rs:199:41:
  thread panicked while generating bindings: Any { .. }
```

Any ideas what is causing it and how to fix it?

**Comment by workingjubilee** [comment]
We do not support pgx 0.7.4 anymore, sorry. Please let us know if you have issues with pgrx 0.11.3 or pgrx 0.12.0-alpha.1
